#!/usr/env/bin python3
# This script parse the sample reads file which is generated by fastp
import argparse
import csv
import re

def main(input_file):
    PATTERN = "|".join(["_1.non_host", "_EKDL[A-Z0-9\\-\\_\\.]+.fq"])
    with open(input_file, newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',')
        rows = [row for row in reader]

    cleaned_rows = [[re.sub(PATTERN, "", row[0]), row[1]] for row in rows]
    
    merged_rows = []
    i = 0
    while i < len(cleaned_rows):
        removed_human = 0
        removed_human_proportion = 0
        if i+1 < len(cleaned_rows):
            cleaned_row1 = cleaned_rows[i]
            cleaned_row2 = cleaned_rows[i+1]
            if cleaned_row1[0] == cleaned_row2[0]:
                removed_human = int(cleaned_row2[1]) - int(cleaned_row1[1])
                removed_human_proportion = round(removed_human/int(cleaned_row2[1])*100,2)
                merged_rows.append([cleaned_row1[0], cleaned_row1[1], cleaned_row2[1], removed_human, removed_human_proportion])
                i += 2
            else:
                merged_rows.append([cleaned_row1,0,0,removed_human, removed_human_proportion])
                i += 1
        else:
            merged_rows.append([cleaned_rows[i],0,0,removed_human, removed_human_proportion])
            i += 1
    print("Sample_Name, Non_Host_Reads, Original_Reads, Removed_human, Removed_human_proportion(%)")
    for row in merged_rows:
        print(",".join([str(x) for x in row]))
    # with open('output.csv', 'w', newline='') as csvfile:
    #     writer = csv.writer(csvfile)
    #     writer.writerow(['Sample_Name', 'Non_Host_Reads', 'Original_Reads', 'Removed_human'])
    #     for row in merged_rows:
    #         writer.writerow(row)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Parsd the sample reads file which is generated by fastp\n and group every two consecutive lines from CSV file.\n')
    parser.add_argument('input_file', type=str, help='path to the input CSV file')
    args = parser.parse_args()

    main(args.input_file)